runtime: nodejs16
service: frontend

handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html

  - url: /(.*)
    static_files: build/\1
    upload: build/(.*)

  - url: /.*
    static_dir: build
